"""Protocol constants for the Remootio Websocket API."""

DEFAULT_PORT = 8080
DEFAULT_PING_INTERVAL = 60.0
DEFAULT_AUTH_TIMEOUT = 15.0
DEFAULT_ACTION_TIMEOUT = 10.0
DEFAULT_HELLO_TIMEOUT = 5.0
INITIAL_RECONNECT_DELAY = 1.0
MAX_RECONNECT_DELAY = 60.0

# Action IDs are 31-bit counters. Next id = (lastActionId + 1) % ACTION_ID_MASK.
ACTION_ID_MASK = 0x7FFFFFFF

HEX_KEY_LENGTH = 64
MIN_API_VERSION_DURATION = 3
